/**
 * Tvara — choose what is worth carrying into the next conversation.
 *
 * WHAT WAS WRONG WITH THE OLD ANSWER
 * The handover took the opening question and the last six turns. On the
 * conversation this feature exists for — hundreds of turns, hours of work — the
 * last six turns are usually "yes that worked, thanks". Everything that was
 * actually decided happened in the middle, and the middle was thrown away.
 *
 * WHAT THIS DOES NOT DO
 * It does not summarise. Every character it emits was typed by the user or the
 * model, verbatim, and it is never edited into something neither of them said.
 * There is no server here and no API key, and a paraphrase generated by a
 * heuristic is a sentence nobody wrote being attributed to somebody — which for
 * a handover is worse than saying less.
 *
 * WHAT IT DOES INSTEAD
 * It selects. The question "which turns matter" has a real answer that can be
 * computed locally and deterministically:
 *
 *   · turns that are ABOUT what the conversation is about — measured by how
 *     much of the conversation's own vocabulary they carry (tf-idf against the
 *     whole thread, cosine to its centroid), so a turn using the words the
 *     thread keeps returning to scores above small talk
 *   · turns where something was DECIDED — a correction, a constraint, a choice
 *     between options. These are the ones a reader of the next chat would ask
 *     about, and they are cheap to spot because people phrase them the same way
 *   · the CURRENT state of any code, which means the newest version of each
 *     distinct block rather than whichever block happened to be last
 *   · what the user marked themselves, which outranks anything inferred
 *
 * and then drops near-duplicates, because a long thread restates itself and
 * carrying the same paragraph three times spends the budget on nothing.
 */
(() => {
  "use strict";

  /* Words that carry no signal about a subject. Kept short on purpose: a big
     stop list starts removing domain words on a thread about grammar. */
  const STOP = new Set(("the a an and or but if then else so of to in on at for with from by as is are was were be been " +
    "being do does did doing have has had having i you he she it we they me him her us them my your his its our their " +
    "this that these those there here what which who whom when where why how all any both each few more most other some " +
    "such no nor not only own same too very can will just should now would could may might must shall about into over " +
    "under again further once ok okay yes yeah thanks thank please sure right good great nice cool sorry hi hello hey")
    .split(" "));

  const tokens = (s) => String(s || "").toLowerCase()
    .replace(/```[\s\S]*?```/g, " ")            // code is scored separately
    .match(/[a-z0-9][a-z0-9'+#.-]{1,}/g) || [];

  /** A turn where something was settled rather than explored. */
  const DECIDED = new RegExp("\\b(instead|actually|don'?t|do not|never|always|must|need to|has to"
    + "|shouldn'?t|let'?s|we'?ll|i'?ll|switch(ed)? to|go with|rather than|the fix|the problem is"
    + "|turns out|because|so that|the reason|decided|final|prefer|requirement|constraint)\\b", "i");

  /** A turn that is only an acknowledgement carries nothing forward. */
  const ACK = /^(ok(ay)?|yes|yep|yeah|sure|thanks?|thank you|great|nice|cool|perfect|got it|done|nope|no)\b[\s!.,]*$/i;

  /* ---------- code ---------- */

  /** Every fenced block, newest occurrence of each distinct block winning.
   *  A thread iterates on the same file: what the next model needs is the last
   *  version of each, not the last version of whichever was pasted most
   *  recently. Keyed on a signature so an edited block replaces its ancestor. */
  function codeBlocks(records, max) {
    const byKey = new Map();
    records.forEach((r, order) => {
      const text = String(r.text || "");
      const re = /```([^\n`]*)\n?([\s\S]*?)```/g;
      let m;
      while ((m = re.exec(text))) {
        const body = (m[2] || "").trim();
        if (body.length < 40) continue;                 // a one-liner is not state
        const lang = (m[1] || "").trim().split(/\s+/)[0] || "";
        /* Identity of a block: the shape of its first meaningful line. Edits
           change the body but rarely the declaration, so a later revision maps
           to the same key and replaces the earlier one. */
        const first = body.split("\n").find((l) => l.trim() && !/^[/#*<-]/.test(l.trim())) || body.slice(0, 60);
        const key = lang + "|" + first.trim().replace(/\s+/g, " ").slice(0, 80);
        byKey.set(key, { lang, body, order });          // later write wins
      }
    });
    return [...byKey.values()].sort((a, b) => a.order - b.order).slice(-max);
  }

  /* ---------- near-duplicate removal ---------- */

  const shingles = (toks) => {
    const out = new Set();
    for (let i = 0; i + 2 < toks.length; i++) out.add(toks[i] + " " + toks[i + 1] + " " + toks[i + 2]);
    return out;
  };

  function overlaps(a, b) {
    if (!a.size || !b.size) return 0;
    const [small, big] = a.size < b.size ? [a, b] : [b, a];
    let shared = 0;
    for (const s of small) if (big.has(s)) shared++;
    return shared / small.size;                          // containment, not Jaccard
  }

  /* ---------- selection ---------- */

  /**
   * @param {Array<{role:string,text:string}>} records the whole conversation
   * @param {{max?:number, starred?:string[]}} opts
   * @returns {{goal, decisions, code, recent, covered, total}}
   */
  function distil(records, opts) {
    const o = opts || {};
    const recs = (records || []).filter((r) => r && r.text && !ACK.test(r.text.trim()));
    const total = (records || []).length;
    if (!recs.length) return { goal: "", decisions: [], code: [], recent: [], covered: 0, total };

    /* Document frequency over turns, so a word used everywhere (the project's
       name, say) weighs less than one that marks a particular exchange. */
    const df = new Map();
    const perTurn = recs.map((r) => {
      const t = tokens(r.text).filter((w) => !STOP.has(w) && w.length > 2);
      const tf = new Map();
      for (const w of t) tf.set(w, (tf.get(w) || 0) + 1);
      for (const w of tf.keys()) df.set(w, (df.get(w) || 0) + 1);
      return tf;
    });
    const N = recs.length;
    const idf = (w) => Math.log(1 + N / (1 + (df.get(w) || 0)));

    /* The conversation's own centre of mass, in its own words. */
    const centroid = new Map();
    perTurn.forEach((tf) => {
      for (const [w, n] of tf) centroid.set(w, (centroid.get(w) || 0) + n * idf(w));
    });
    let cNorm = 0;
    for (const v of centroid.values()) cNorm += v * v;
    cNorm = Math.sqrt(cNorm) || 1;

    const scored = recs.map((r, i) => {
      const tf = perTurn[i];
      let dot = 0, norm = 0;
      for (const [w, n] of tf) {
        const v = n * idf(w);
        norm += v * v;
        dot += v * (centroid.get(w) || 0);
      }
      norm = Math.sqrt(norm) || 1;
      const centrality = dot / (norm * cNorm);           // 0..1, about-ness

      const len = r.text.length;
      let s = centrality * 100;
      if (DECIDED.test(r.text)) s += 45;                 // something was settled
      if (r.role === "user") s += 12;                    // the user sets direction
      if (/```/.test(r.text)) s += 8;                    // carries state
      if (len < 80) s -= 25;                             // too small to say much
      if (len > 4000) s -= 10;                           // a wall is rarely the point
      return { ...r, i, score: s };
    });

    /* Starred beats anything computed: the user already answered this question
       for the parts they cared about. */
    const starred = (o.starred || []).map((t) => String(t || "").trim()).filter(Boolean);
    if (starred.length) {
      const marks = starred.map((t) => shingles(tokens(t)));
      for (const cand of scored) {
        const sh = shingles(tokens(cand.text));
        if (marks.some((m) => overlaps(m, sh) > 0.6)) cand.score += 120;
      }
    }

    const maxChars = o.max || 2600;
    const picked = [];
    const seen = [];
    let used = 0;
    for (const cand of [...scored].sort((a, b) => b.score - a.score)) {
      if (used >= maxChars || picked.length >= 10) break;
      if (cand.score <= 0) break;
      const sh = shingles(tokens(cand.text));
      // A thread restates itself; carrying the same paragraph twice buys nothing.
      if (seen.some((prev) => overlaps(prev, sh) > 0.55)) continue;
      seen.push(sh);
      picked.push(cand);
      used += Math.min(cand.text.length, 600);
    }
    picked.sort((a, b) => a.i - b.i);                    // back into the order it happened

    const goalFrom = recs.find((r) => r.role === "user" && r.text.length > 12) || recs[0];
    return {
      goal: goalFrom ? goalFrom.text : "",
      decisions: picked,
      code: codeBlocks(recs, 2),
      recent: recs.slice(-4),
      covered: picked.length ? Math.round(((picked[picked.length - 1].i - picked[0].i + 1) / N) * 100) : 0,
      total
    };
  }

  self.LCTDistil = { distil, codeBlocks, tokens, overlaps, shingles };
})();
