#!/usr/bin/env node
/**
 * Tvara — standalone legal pages.
 *
 *   node tools/legal-pages.mjs           # write docs/privacy.html, docs/terms.html
 *   node tools/legal-pages.mjs --check   # exit 1 if either is stale
 *
 * WHY. The policies live in docs/index.html as #privacy and #terms, and every
 * link we have ever published points at those anchors. Google's OAuth consent
 * screen and several store forms want a URL per policy instead, and some of
 * them reject a fragment outright.
 *
 * Copying the text into two more files would put the same paragraph in three
 * places and let them drift, which for a privacy policy is a compliance
 * problem, not an untidiness. So these pages are GENERATED from index.html and
 * preflight fails when they no longer match it. index.html stays canonical;
 * the anchors keep working for everything already shipped.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "docs", "index.html");
const CHECK = process.argv.includes("--check");

const src = readFileSync(SRC, "utf8");

/* The stylesheet, lifted whole. A second copy of the CSS would drift from the
   pricing page the first time a colour changed. */
const style = (src.match(/<style>[\s\S]*?<\/style>/) || [])[0];
if (!style) throw new Error("no <style> block in docs/index.html");

/** One <section id="…">…</section>, verbatim. Sections here are never nested. */
function section(id) {
  const re = new RegExp(`<section id="${id}"[^>]*>[\\s\\S]*?</section>`);
  const found = (src.match(re) || [])[0];
  if (!found) throw new Error(`no #${id} section in docs/index.html`);
  return found;
}

/* `class="legal"` on a <section> is what index.html uses to set the reading
   width and the smaller type; the pages keep it so the text reads the same. */
const page = (title, description, body) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<!-- The licence key can arrive in the query string; never let it leave in a Referer. -->
<meta name="referrer" content="no-referrer" />
<title>${title} · Tvara</title>
<meta name="description" content="${description}" />
<!-- GENERATED by tools/legal-pages.mjs from docs/index.html. Edit the section
     there, then re-run it; preflight fails while this file is stale. -->
${style}
</head>
<body>
<div class="wrap">

<header style="padding:56px 0 24px;">
  <div class="logo">⚡</div>
  <h1 style="font-size:32px;">${title}</h1>
  <nav><a href="./">Tvara</a> · <a href="./privacy.html">Privacy</a> · <a href="./terms.html">Terms</a> · <a href="mailto:tvara.exten@gmail.com">Contact</a></nav>
</header>

${body}

<footer>
  <p>Questions: <a href="mailto:tvara.exten@gmail.com">tvara.exten@gmail.com</a></p>
</footer>

</div>
</body>
</html>
`;

const targets = [
  {
    file: join(ROOT, "docs", "privacy.html"),
    html: page("Privacy Policy",
      "What Tvara stores, what it sends, and what it can never see. Conversations stay on your device.",
      section("privacy"))
  },
  {
    /* Refunds ride along with the terms: a buyer looking for the refund rule
       looks under terms, and Dodo's checkout links one URL, not two. */
    file: join(ROOT, "docs", "terms.html"),
    html: page("Terms of Service",
      "The terms of using Tvara, the licence you buy, devices, and the 14-day refund.",
      section("terms") + "\n\n" + section("refunds"))
  }
];

let stale = 0;
for (const { file, html } of targets) {
  const current = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (current === html) { if (!CHECK) console.log("unchanged", file); continue; }
  if (CHECK) { stale++; console.error("STALE", file); continue; }
  writeFileSync(file, html);
  console.log("wrote", file);
}

if (CHECK && stale) {
  console.error(`${stale} legal page(s) no longer match docs/index.html — run: node tools/legal-pages.mjs`);
  process.exit(1);
}
