#!/usr/bin/env node
/**
 * Does the key on this machine still match the one the world trusts?
 *
 *   node tools/verify-keys.mjs
 *
 * The public half of the signing key is compiled into every copy of the
 * extension that has ever been installed. If the private half on this laptop
 * stops matching it — restored from the wrong backup, regenerated by accident,
 * a half-finished `genkey init` — then every key issued from here is
 * unverifiable by every customer, and the failure is silent: `genkey issue`
 * happily prints a key that simply does not work.
 *
 * So this checks the two halves against each other, and checks both shipped
 * verifiers agree, by actually signing something and verifying it.
 */
import { readFileSync, existsSync } from "node:fs";
import { createPrivateKey, createPublicKey, sign, verify } from "node:crypto";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const PRIV = join(homedir(), ".lct-keys", "private.pem");

let ok = true;
const say = (good, msg, detail) => {
  if (!good) ok = false;
  console.log(`  ${good ? "✓" : "✗"} ${msg}${detail ? "  " + detail : ""}`);
};

console.log("");
if (!existsSync(PRIV)) {
  console.log(`  ✗ no private key at ${PRIV}`);
  console.log("\n  Restore it from your encrypted backup, then run this again.\n");
  process.exit(1);
}

const priv = createPrivateKey(readFileSync(PRIV));
const derived = createPublicKey(priv).export({ type: "spki", format: "der" }).toString("base64");

// Both verifiers must carry the same key: a token verifies against one file, an
// LCT1 licence against the other, and a mismatch breaks exactly half of them.
for (const f of ["lib/license.js", "lib/entitlement.js"]) {
  const src = readFileSync(join(root, f), "utf8");
  const m = src.match(/const PUBLIC_KEY_B64 = "([^"]*)"/);
  say(!!m, `${f} declares a public key`);
  if (m) say(m[1] === derived, `${f} matches the private key on this machine`,
             m[1] === derived ? "" : "\n      shipped: " + m[1].slice(0, 32) + "…\n      derived: " + derived.slice(0, 32) + "…");
}

// And prove it end to end rather than by string comparison alone.
const payload = Buffer.from("tvara-key-selftest");
const sig = sign("sha256", payload, { key: priv, dsaEncoding: "ieee-p1363" });
const pub = createPublicKey({ key: Buffer.from(derived, "base64"), format: "der", type: "spki" });
say(verify("sha256", payload, { key: pub, dsaEncoding: "ieee-p1363" }, sig),
    "a signature made with this key verifies against it");

console.log(ok
  ? "\n  This key can still issue licences every installed copy will accept.\n"
  : "\n  ✋ DO NOT ISSUE KEYS. Restore the correct private.pem from backup first.\n");
process.exit(ok ? 0 : 1);
